name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build Docker Image
      run: |
          docker build . --file Dockerfile --tag my-image-name:latest
          docker tag my-image-name:latest "${{ secrets.DOCKER_USERNAME }}"/github-action-test
          docker push "${{ secrets.DOCKER_USERNAME }}"/github-action-test:latest
    -name : Create Docker
    
