name: Comment
on:
  issues:
    types: [opened]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo'${{ toJSON(github.events)}}' | jq
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ toJSON(github.events.issue.number)}}
          body: |
            Thanks for raising the issue 
            Our team will look into it
          reactions: '+1'